# sample docker build pipeline

trigger: none

variables:
- name: ACR_NAME
  value: youracr.azurecr.io
- name: MODEL_URL
  value: https://yourblob.blob.core.windows.net/model/models/fruits-01-0.7265.h5

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'MyAzureSubscription'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr build -r $(ACR_NAME) -f Dockerfile \
        --build-arg MODELURL=$(MODEL_URL) --build-arg BUILDID=$(Build.BuildId) \
        -t $(ACR_NAME)/fruitsdevops:$(Build.BuildId) -t $(ACR_NAME)/fruitsdevops:latest .
