# sample docker build pipeline

trigger: none

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'MyAzureSubscription'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr build -r $(AC_NAME) -f Dockerfile-nginx \
        -t $(ACRNAME)/nginx:$(Build.BuildId) -t $(ACRNAME)/nginx:latest .
