# sample pull request pipeline

trigger: none

pool:
  name: lxpool
  
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      pylint -f msvs -E --disable=F0401 *.py 2> /dev/null
    failOnStderr: true